imports:
    - { resource: '../features/framework.yaml' }
    - { resource: '../features/doctrine.yaml' }
    - { resource: '../features/services.yaml' }
jsonapi:
    cache:
        etag:
            hash_algo: sha256
            weak_for_collections: false
            include_query_shape: true
        headers:
            public: false
            max_age: 15
            s_maxage: 30
            stale_while_revalidate: 45
            stale_if_error: 60
            add_age: true
        vary:
            accept_language: true
        surrogate_keys:
            header_name: X-Cache-Tags
            format:
                resource: 'item-{type}-{id}'
                collection: 'list-{type}'
                relationship: 'rel-{type}-{id}-{rel}'
