imports:
    - { resource: '../features/framework.yaml' }
    - { resource: '../features/doctrine.yaml' }
    - { resource: '../features/services.yaml' }
jsonapi:
    resource_paths:
        - '%kernel.project_dir%/tests/Fixtures/Contracts'
services:
    cookbook.tagged_article:
        class: App\Tests\Fixtures\Tagged\TaggedArticle
        autoconfigure: false
        tags: [{ name: jsonapi.resource, type: tagged-articles }]
