imports:
    - { resource: '../features/framework.yaml' }
    - { resource: '../features/doctrine.yaml' }
    - { resource: '../features/services.yaml' }
jsonapi:
    errors:
        expose_debug_meta: true
        add_correlation_id: false
        default_title_map: false
