imports:
    - { resource: '../features/framework.yaml' }
    - { resource: '../features/doctrine.yaml' }
    - { resource: '../features/services.yaml' }
jsonapi:
    relationships:
        unplanned_read_policy: reject
services:
    cookbook.suggested_author_reader:
        class: App\JsonApi\DataLayer\SuggestedAuthorsBatchReader
        autowire: true
        tags: ['jsonapi.relationship_batch_reader']
