imports:
    - { resource: '../features/framework.yaml' }
    - { resource: '../features/doctrine.yaml' }
    - { resource: '../features/services.yaml' }
jsonapi:
    resource_paths: ['%kernel.project_dir%/src/FeatureMemory']
    data_layer:
        provider: custom
        repository: App\JsonApi\DataLayer\MemoryArticleProvider
        processor: App\JsonApi\DataLayer\MemoryArticleProvider
        relationship_reader: App\JsonApi\DataLayer\MemoryArticleProvider
        transaction_manager: App\JsonApi\DataLayer\MemoryArticleProvider
    cache:
        enabled: false
    profiles:
        per_type:
            tags: []
services:
    AlexFigures\JsonApi\Contract\Data\RepresentationPreloaderInterface: '@App\JsonApi\DataLayer\MemoryArticleProvider'
    cookbook.memory_probe:
        class: App\EventSubscriber\MemoryProviderProbe
        autowire: true
        tags: [{ name: kernel.event_listener, event: kernel.response, method: onResponse, priority: -100 }]
