import json
from collections import Counter
from pathlib import Path
inventory=json.loads(Path('docs/public-feature-inventory.json').read_text())
# Evidence points to independent application tests, never bundle-owned unit tests.
rules=[
('jsonapi.media_type','Protocol/ContentNegotiationTest.php','PARTIAL',''),
('Contract/Data/ChangeSet','Features/DataLayer/CustomProviderTest.php','COVERED_GREEN',''),
('Contract/Data/ResourceIdentifier','Features/Relationships/LinkingPoliciesTest.php','COVERED_GREEN',''),
('Contract/Data/SliceIds','Features/Relationships/RootJoinPaginationTest.php','PARTIAL',''),
('Contract/Data/Slice','Features/DataLayer/CustomProviderTest.php','COVERED_GREEN',''),
('Contract/Data/ExistenceChecker','Features/Relationships/LinkingPoliciesTest.php','PARTIAL',''),
('Contract/Data/RepresentationPreloaderInterface','Features/DataLayer/BatchRelationshipReaderTest.php','PARTIAL',''),
('Contract/Data/WriteConcurrencyGuardInterface','Production/ConcurrencyAndAtomicTest.php','PARTIAL',''),
('Contract/Data/ResourcePersister','Features/DataLayer/TypedProviderTest.php','COVERED_GAP','DX-TYPED-PERSISTER-DISPATCH'),
('Contract/Resource/ResourceMetadataInterface','Features/DataLayer/CustomProviderTest.php','PARTIAL',''),
('Contract/Tx/NullTransactionManager','','NOT_APPLICABLE',''),
('Resource/Definition/ReadProjection','Features/Mapping/ConstructorAndProjectionTest.php','COVERED_GREEN',''),
('Resource/Definition/ResourceDefinition','Features/Mapping/ConstructorAndProjectionTest.php','PARTIAL',''),
('Resource/Definition/VersionDefinition','Features/Mapping/PublicInputAndVersionTest.php','COVERED_GAP','VERSION-RESOLVER-CONTEXT'),
('Resource/Mapper/DefaultReadMapper','Features/Mapping/ConstructorAndProjectionTest.php','COVERED_GREEN',''),
('Resource/Registry/CustomRouteRegistry','Features/CustomRoutes/HandlerContractTest.php','PARTIAL',''),
('Resource/Registry/ResourceRegistry','Features/DataLayer/CustomProviderTest.php','PARTIAL',''),
('ServiceTag/jsonapi.relationship_batch_reader','Features/DataLayer/BatchRelationshipReaderTest.php','COVERED_GREEN',''),
('jsonapi.relationships.unplanned_read_policy','Features/DataLayer/UnplannedRelationshipTest.php','COVERED_GREEN',''),
('jsonapi.cache.enabled','Features/Cache/DisabledCacheTest.php','COVERED_GREEN',''),
('jsonapi.limits.fields_max_total','Features/Relationships/DocumentBudgetTest.php','COVERED_GREEN',''),
('jsonapi.limits.included_max_resources','Features/Relationships/DocumentBudgetTest.php','COVERED_GREEN',''),
('jsonapi.performance.doctrine.enable_query_cache','','CONFIG_ONLY',''),
('jsonapi.performance.doctrine.query_cache_pool','','CONFIG_ONLY',''),
('jsonapi.performance.doctrine.enable_second_level_cache','','CONFIG_ONLY',''),
('jsonapi.performance.doctrine.hydrate_partial_by_fields','','CONFIG_ONLY',''),
('jsonapi.performance.doctrine.default_fetch','','CONFIG_ONLY',''),
('jsonapi.errors.locale','','CONFIG_ONLY',''),
('jsonapi.errors.','Features/Protocol/ErrorConfigurationTest.php','COVERED_GREEN',''),
('jsonapi.cache.etag.strategy','Features/Cache/VersionStrategyTest.php','COVERED_GAP','CACHE-VERSION-STRATEGY'),
('jsonapi.cache.etag.include_query_shape','Features/Cache/QueryShapeTest.php','PARTIAL',''),
('jsonapi.cache.last_modified.collections_max_of','Features/Cache/DisabledCollectionLastModifiedTest.php','COVERED_GAP','CACHE-COLLECTION-LAST-MODIFIED'),
('jsonapi.cache.last_modified.','Features/Cache/LastModifiedConfigurationTest.php','COVERED_GREEN',''),
('jsonapi.atomic.enabled','Features/Atomic/DisabledAtomicTest.php','COVERED_GREEN',''),
('jsonapi.atomic.endpoint','Features/Atomic/EndpointTest.php','COVERED_GREEN',''),
('jsonapi.profiles.audit_trail.expose_in_meta','Features/Profiles/AuditIdentityTest.php','COVERED_GAP','PROFILE-AUDIT-META'),
('jsonapi.profiles.audit_trail.','Features/Profiles/AuditIdentityTest.php','PARTIAL',''),
('Contract/Data/TypedResourcePersister','Features/DataLayer/TypedProviderTest.php','COVERED_GAP','DX-TYPED-PERSISTER-DISPATCH'),
('Contract/Data/TypedRelationshipReader','','DOCUMENTATION_ONLY',''),
('Contract/Data/TypedRelationshipUpdater','','DOCUMENTATION_ONLY',''),
('Resource/Mapper/WriteMapperInterface','Features/Mapping/PublicInputAndVersionTest.php','PARTIAL','WRITE-REQUEST-DTO'),
('Resource/Mapper/DefaultWriteMapper','Features/Mapping/PublicInputAndVersionTest.php','PARTIAL','WRITE-REQUEST-DTO'),
('Contract/Data/RelationshipBatchReaderInterface','Features/DataLayer/BatchRelationshipReaderTest.php','COVERED_GREEN',''),
('Profile/Hook/FilterParameterProviderInterface','Features/Profiles/SoftDeleteConfigurationTest.php','PARTIAL',''),
('Profile/Hook/FetchPlanHookInterface','Features/Profiles/PublicHooksTest.php','COVERED_GREEN',''),
('ServiceTag/jsonapi.filter.operator','Features/Filtering/InheritanceAndExtensionsTest.php','COVERED_GAP','EXTENSIBILITY-CUSTOM-OPERATOR'),
('ServiceTag/jsonapi.filter.handler','Features/Filtering/HandlerPriorityTest.php','PARTIAL','FILTER-HANDLER-LOGICAL-COMPOSITION'),
('ServiceTag/jsonapi.sort.handler','Features/Sorting/AggregateSemanticsTest.php','COVERED_GREEN',''),
('ServiceTag/jsonapi.resource_repository','Features/DataLayer/TypedProviderTest.php','COVERED_GREEN',''),
('ServiceTag/jsonapi.custom_route_handler','Features/CustomRoutes/HandlerContractTest.php','COVERED_GREEN',''),
('ServiceTag/jsonapi.profile','Features/Profiles/PublicHooksTest.php','PARTIAL',''),
('ServiceTag/jsonapi.resource','Features/Docs/OpenApiTest.php','PARTIAL',''),
('jsonapi.pagination.', 'Query/PaginationTest.php', 'PARTIAL',''),
('jsonapi.strict_content_negotiation','Protocol/ContentNegotiationTest.php','COVERED_GREEN',''),
('jsonapi.route_prefix','Resource/ResourceReadTest.php','COVERED_GREEN',''),
('jsonapi.resource_paths','Features/DataLayer/TypedProviderTest.php','PARTIAL',''),
('jsonapi.data_layer.', 'Features/DataLayer/CustomProviderTest.php','PARTIAL','DATA-LAYER-CUSTOM-ATOMIC'),
('jsonapi.write.', 'Resource/ResourceCreateTest.php','PARTIAL',''),
('jsonapi.relationships.linkage_in_resource','Features/Relationships/RepresentationModesTest.php','COVERED_GREEN',''),
('jsonapi.relationships.write_response','Features/Relationships/RepresentationModesTest.php','PARTIAL',''),
('jsonapi.limits.filter_', 'Features/Filtering/StructuralLimitsTest.php','COVERED_GREEN',''),
('jsonapi.limits.complexity_budget','Features/Filtering/StructuralLimitsTest.php','COVERED_GREEN',''),
('jsonapi.limits.relationship_max_identifiers','Features/Relationships/IdentifierBudgetTest.php','COVERED_GAP','RELATIONSHIP-BUDGET-ENDPOINT'),
('jsonapi.limits.include_', 'Query/IncludeTest.php','PARTIAL',''),
('jsonapi.limits.page_max_size','Query/PaginationTest.php','COVERED_GREEN',''),
('jsonapi.performance.doctrine.collection_sort_policy','Features/Sorting/AggregateSemanticsTest.php','COVERED_GREEN',''),
('jsonapi.performance.head_enabled','Protocol/HeadTest.php','PARTIAL',''),
('jsonapi.cache.etag.hash_algo','Features/Cache/HeaderConfigurationTest.php','COVERED_GREEN',''),
('jsonapi.cache.etag.weak_for_collections','Features/Cache/HeaderConfigurationTest.php','COVERED_GREEN',''),
('jsonapi.cache.etag.', 'Cache/ConditionalRequestsTest.php','PARTIAL',''),
('jsonapi.cache.headers.', 'Features/Cache/HeaderConfigurationTest.php','COVERED_GREEN',''),
('jsonapi.cache.vary.', 'Features/Cache/HeaderConfigurationTest.php','COVERED_GREEN',''),
('jsonapi.cache.surrogate_keys.', 'Features/Cache/HeaderConfigurationTest.php','COVERED_GAP','CACHE-SURROGATE-ROUTES'),
('jsonapi.cache.conditional.', 'Cache/WritePreconditionsTest.php','PARTIAL',''),
('jsonapi.cache.last_modified.', 'Cache/ConditionalRequestsTest.php','PARTIAL',''),
('jsonapi.atomic.return_policy','Features/Atomic/ConfigurationMatrixTest.php','COVERED_GREEN',''),
('jsonapi.atomic.require_ext_header','Features/Atomic/ConfigurationMatrixTest.php','COVERED_GREEN',''),
('jsonapi.atomic.max_operations','Features/Atomic/ConfigurationMatrixTest.php','COVERED_GREEN',''),
('jsonapi.atomic.allow_href','Features/Atomic/ConfigurationMatrixTest.php','COVERED_GREEN',''),
('jsonapi.atomic.lid.', 'Features/Atomic/ConfigurationMatrixTest.php','COVERED_GAP','ATOMIC-LID-CONFIG'),
('jsonapi.atomic.', 'Atomic/AtomicTransactionalityTest.php','PARTIAL',''),
('jsonapi.docs.generator.json_schema.include_profiles','Features/Docs/OpenApiTest.php','PARTIAL',''),
('jsonapi.docs.generator.json_schema.', 'Features/Docs/OpenApiTest.php','COVERED_GAP','CONFIG-JSON-SCHEMA'),
('jsonapi.docs.generator.openapi.', 'Features/Docs/RedocTest.php','PARTIAL','DOCS-OPERATIONS'),
('jsonapi.docs.ui.', 'Features/Docs/DisabledUiTest.php','PARTIAL','DOCS-NEGOTIATION'),
('jsonapi.dx.', '', 'CONFIG_ONLY',''),
('jsonapi.release.', '', 'CONFIG_ONLY',''),
('jsonapi.profiles.soft_delete.strategy','Features/Profiles/BooleanSoftDeleteTest.php','COVERED_GAP','PROFILE-SOFT-BOOLEAN'),
('jsonapi.profiles.soft_delete.default_visibility','Features/Profiles/SoftDeleteConfigurationTest.php','COVERED_GAP','PROFILE-SOFT-VISIBILITY'),
('jsonapi.profiles.soft_delete.delete_semantics','Features/Profiles/SoftDeleteConfigurationTest.php','COVERED_GAP','PROFILE-SOFT-DELETE-SEMANTICS'),
('jsonapi.profiles.soft_delete.query_flags.with_deleted','Features/Profiles/SoftDeleteConfigurationTest.php','COVERED_GAP','PROFILE-SOFT-QUERY-FLAGS'),
('jsonapi.profiles.soft_delete.', 'Features/Profiles/SoftDeleteConfigurationTest.php','PARTIAL','PROFILE-SOFT-VISIBILITY'),
('jsonapi.profiles.', 'Profiles/ProfileTest.php','PARTIAL',''),
('Bridge/Symfony/Routing/Attribute/MediaChannel','Features/Protocol/MediaChannelsTest.php','COVERED_GAP','MEDIA-CHANNEL-ROUTING'),
('jsonapi.media_types.', 'Atomic/AtomicNegotiationTest.php','PARTIAL',''),
('jsonapi.errors.', 'Protocol/ErrorDocumentTest.php','PARTIAL',''),
('Resource/Attribute/JsonApiResource::$writeRequests','Features/Mapping/PublicInputAndVersionTest.php','COVERED_GAP','WRITE-REQUEST-DTO'),
('Resource/Attribute/JsonApiResource::$versionResolver','Features/Mapping/PublicInputAndVersionTest.php','COVERED_GAP','VERSION-RESOLVER-CONTEXT'),
('Resource/Attribute/JsonApiResource::$fieldMap','Features/Mapping/ConstructorAndProjectionTest.php','COVERED_GREEN',''),
('Resource/Attribute/FilterableField','Features/Filtering/InheritanceAndExtensionsTest.php','PARTIAL','EXTENSIBILITY-CUSTOM-OPERATOR'),
('Resource/Attribute/SortableField','Features/Filtering/InheritanceAndExtensionsTest.php','PARTIAL',''),
('Resource/Attribute/Relationship','Features/Relationships/PathAliasTest.php','PARTIAL',''),
('Resource/Attribute/JsonApiCustomRoute','Features/CustomRoutes/HandlerContractTest.php','PARTIAL','CUSTOM-ACTION-QUERY-PARAMETER'),
('Resource/Attribute/', 'Mapping/FieldAliasesTest.php','PARTIAL',''),
('Docs/Attribute/', 'Features/Docs/OpenApiTest.php','PARTIAL',''),
('Contract/Data/TypedResourceRepository','Features/DataLayer/TypedProviderTest.php','COVERED_GREEN',''),
('Contract/Data/ResourceRepository','Features/DataLayer/CustomProviderTest.php','COVERED_GREEN',''),
('Contract/Data/ResourceProcessor','Features/DataLayer/CustomProviderTest.php','COVERED_GREEN',''),
('Contract/Data/RelationshipReader','Features/DataLayer/CustomProviderTest.php','COVERED_GREEN',''),
('Contract/Data/RelationshipUpdater','Production/RelationshipPolicyTest.php','COVERED_GREEN',''),
('Contract/Tx/ScopedTransactionManagerInterface','Features/CustomRoutes/HandlerContractTest.php','COVERED_GREEN',''),
('Contract/Tx/TransactionManager','Features/DataLayer/CustomProviderTest.php','PARTIAL',''),
('Profile/Hook/ReadHook','Features/Profiles/PublicHooksTest.php','COVERED_GAP','PROFILE-READ-HOOK'),
('Profile/Hook/RelationshipHook','Features/Profiles/PublicHooksTest.php','COVERED_GAP','PROFILE-RELATIONSHIP-HOOK'),
('Profile/Hook/FetchPlanHookInterface','Features/Profiles/PublicHooksTest.php','PARTIAL',''),
('Profile/Hook/','Features/Profiles/PublicHooksTest.php','PARTIAL',''),
('Profile/Attribute/','Profiles/ProfileTest.php','PARTIAL',''),
('Filter/Operator/','Query/FilteringTest.php','PARTIAL',''),
('Filter/Handler/FilterHandlerInterface','Production/QueryScopeTest.php','PARTIAL',''),
('Filter/Handler/SortHandlerInterface','Features/Sorting/AggregateSemanticsTest.php','PARTIAL',''),
('CustomRoute/Attribute/NoTransaction','Features/CustomRoutes/HandlerContractTest.php','COVERED_GREEN',''),
('CustomRoute/Handler/','Features/CustomRoutes/HandlerContractTest.php','COVERED_GREEN',''),
('CustomRoute/Result/CustomRouteResult','Features/CustomRoutes/HandlerContractTest.php','PARTIAL',''),
('CustomRoute/Query/CriteriaBuilder','Features/CustomRoutes/HandlerContractTest.php','COVERED_GREEN',''),
('CustomRoute/Context/','Features/CustomRoutes/HandlerContractTest.php','PARTIAL','CUSTOM-ACTION-QUERY-PARAMETER'),
('Resource/Definition/VersionResolverInterface','Features/Mapping/PublicInputAndVersionTest.php','COVERED_GAP','VERSION-RESOLVER-CONTEXT'),
('Resource/Definition/ReadProjection::CUSTOM','Features/Mapping/ConstructorAndProjectionTest.php','COVERED_GREEN',''),
('Resource/Mapper/ReadMapperInterface','Features/Mapping/ConstructorAndProjectionTest.php','COVERED_GREEN',''),
('Resource/Definition/ReadProjection::DTO','Features/Mapping/ConstructorAndProjectionTest.php','COVERED_GREEN',''),
('Resource/Definition/ReadProjection::ENTITY','Resource/ResourceReadTest.php','COVERED_GREEN',''),
('Resource/Definition/ResourceOperation','Protocol/OperationRestrictionsTest.php','PARTIAL','DOCS-OPERATIONS'),
('Resource/Metadata/RelationshipLinkingPolicy','Relationships/ToOneRelationshipTest.php','PARTIAL',''),
('Events/','Features/Events/ResourceEventsTest.php','COVERED_GREEN',''),
('Http/Response/JsonApiResponseFactory','Features/CustomRoutes/ResponseFactoryTest.php','PARTIAL',''),
('Http/Response/JsonApiResponseBuilder','Features/CustomRoutes/ResponseFactoryTest.php','COVERED_GREEN',''),
('Profile/ProfileInterface','Production/ExtensibilityTest.php','PARTIAL','EXTENSIBILITY-PROFILE-DI'),
]
report_path=Path('docs/acceptance-results.json')
report=json.loads(report_path.read_text()) if report_path.exists() else {}
gap_states={g['id']:g['status'] for g in report.get('gap_summary', [])} if report.get('bundle_revision')==inventory['bundle_revision'] else {}
rows=[]
for item in inventory['features']:
 name=item['feature']; test='';status='NOT_COVERED';gap=''
 for prefix,test0,status0,gap0 in rules:
  if name.startswith(prefix):test,status,gap=test0,status0,gap0;break
 if gap and gap_states.get(gap)=='RESOLVED_ON_TESTED_REVISION' and status=='COVERED_GAP': status='COVERED_GREEN'
 if status=='NOT_APPLICABLE': finding='Value/default implementation without a separate application-facing HTTP operation.'
 elif status=='DOCUMENTATION_ONLY': finding='Public legacy interface claims typed dispatch but has no discovered active registration path; see configuration-dx-audit.md.'
 elif status=='NOT_COVERED': finding='No independent execution evidence yet.'
 elif status=='CONFIG_ONLY': finding='Source audit: schema/parameter storage exists, no corresponding feature implementation located.'
 else: finding='See gap inventory.' if gap else 'Variant coverage must be read from the referenced assertions; PARTIAL is not full conformance.'
 rows.append(dict(feature=name,public_api=item['public_api'],status=status,test=test,gap=gap,finding=finding))
counts=Counter(r['status'] for r in rows)
lines=['# Public feature coverage','',f"Installed bundle: `{inventory['bundle_revision']}`. Inventory generated by `php tools/public-feature-inventory.php` from the public configuration tree, attributes, contracts, enums and extension/result methods. No bundle-owned test counts as evidence.",'',f"Explicit inventory: **{len(rows)} entries**. "+', '.join(f'{k}: {v}' for k,v in sorted(counts.items()))+'. No percentage: constructor options, configuration leaves and feature contracts are deliberately separate entries.','', 'COVERED_GREEN means the referenced consumer assertions exercise the recorded contract. PARTIAL means variants or composition remain unverified. CONFIG_ONLY records a source-audited surface without implemented runtime tooling; it is not a passing feature. HTTP results and open gaps are in [acceptance-status.md](acceptance-status.md).','', '## Public surface inventory','', '| Feature | Public API/configuration | Example scenario | Existing coverage / new test | Status | Gap ID | DX/documentation finding |','|---|---|---|---|---|---|---|']
for r in rows:
 evidence=('[test](../tests/Acceptance/'+r['test']+')' if r['test'] else '—')
 lines.append('| '+' | '.join([r['feature'],r['public_api'],r['test'].split('/')[0] if r['test'] else ('Source audit' if r['status'] in ['CONFIG_ONLY','DOCUMENTATION_ONLY','NOT_APPLICABLE'] else 'Pending'),evidence,r['status'],r['gap'] or '—',r['finding']])+' |')
lines+=['','## Coverage that remains explicit','', 'Further identifier, profile/count, caching and media combinations remain partial. Competing-handler priorities, deeper inheritance, shared/operation validation groups, selective operations, duplicate/invalid discovery, audit user identity, batch relationship readers and Atomic endpoint/disable variants now have dedicated external assertions. Typed write dispatch and version-based ETags are verified gaps. Typed relationship contracts have no discovered active registration path and are DOCUMENTATION_ONLY, not a passing feature. Soft-delete, channel matching, CUSTOM mapper, scoped transactions and five composition journeys now have dedicated tests; this does not imply exhaustive variant coverage. Individual rows above retain PARTIAL/NOT_COVERED rather than implying complete external verification.','', 'Existing Production authorization, concurrency, lifecycle and scope tests are unchanged. Existing torture query-count, shard/replica and cross-manager scenarios remain in tests/Torture; a complete torture/performance run is separate from the normal acceptance suite.']
Path('docs/feature-coverage.md').write_text('\n'.join(lines)+'\n')
Path('docs/feature-coverage.json').write_text(json.dumps(dict(bundle_revision=inventory['bundle_revision'],counts=dict(counts),features=rows),indent=2)+'\n')
print(dict(counts))
